classes: [
    '.', 'х', 'ю', 'в', 'ч', 'р', 'и', 'п', 'ш', 'т', 'я', 'э',
    'о', 'ж', 'б', 'д', 'ц', 'е', '-', 'к', 'г', 'ф', 'а', 'й', '6', 'ы',
    'ё', 'л', '9', 'ъ', 'з', '0', 'с', '1', 'м', 'у', ',', 'н', 'щ', 'ь']

data_params:
    batch_size: 12
    num_workers: 16

train_params:
    name: SSDExample
    loss: FocalLoss
    loss_params:
        alpha: 1
        gamma: 2
    epochs: 5
    model_dir: weights
    log_dir: logs
    optimizer: Adam
    optimizer_params:
        lr: 0.0003
    scheduler: StepLR
    scheduler_params:
        step_size: 20
        gamma: 0.5
    metrics: []

bbox_params:
    image_size: [64, 128]
    areas: [120, 240, 360, 480, 960]
    aspect_ratios: [0.5]
    scale_ratios: [1.0, 1.2599210498948732, 1.5874010519681994]
    backbone_strides: [4, 8, 16, 32, 64]
    iou_threshold: 0.5
    score_threshold: 0.2
    nms_threshold: 0.2
    class_independent_nms: False

backbone_params:
    pretrained: True
    archtecture: resnet18

subnet_params:
    num_layers: 4
