model_name: SSDTest

epochs: 1
batch_size: 16
num_workers: 8

model_dir: models
log_dir: logs


network: FPNSSD
network_args:
    num_classes: 42
    encoder: ResNetFPN
    encoder_args:
        n_layer: 50
        pretrained: true
        frozen: false

metrics: []

loss: SSDLoss
loss_args:
    num_classes: 42

optimizer: Adam
optimizer_args:
    lr: 0.0001

# Type of augmentation
augmentation: hard

# Input image size
image_size: [128, 128]

# Area of anchor side in pixels
anchor_areas: [64, 256, 1024.0, 4096.0]

# Aspect ratios of anchors at each cell (width / height).
# A value of 1 represents a square anchor, and 0.5 is a wide anchor
aspect_ratios: [1.0, 2.0, 0.5, 4.0, 0.25]

# Scale ratios of anchors at each cell (width / height)
# width -> scale * width
# height -> scale * height
scale_ratios: [1.0, 2.0, 1.5]

# The strides of each layer of the FPN Pyramid. These values are based on a Resnet backbone.
backbone_strides: [4, 8, 16, 32]

classes: []