classes: [
    '.', 'х', 'ю', 'в', 'ч', 'р', 'и', 'п', 'ш', 'т', 'я', 'э',
    'о', 'ж', 'б', 'д', 'ц', 'е', '-', 'к', 'г', 'ф', 'а', 'й', '6', 'ы',
    'ё', 'л', '9', 'ъ', 'з', '0', 'с', '1', 'м', 'у', ',', 'н', 'щ', 'ь']

data_params:
    batch_size: 8
    num_workers: 16

train_params:
    name: SSDTest
    loss: SSDLoss
    loss_params:
        alpha: 1
        negative_ratio: 3
    epochs: 1
    model_dir: models
    log_dir: logs
    optimizer: Adam
    optimizer_params:
        lr: 0.0003
    scheduler: StepLR
    scheduler_params:
        step_size: 20
        gamma: 0.5
    metrics: []

bbox_params:
    image_size: [64, 64]
    areas: [64, 256, 1024, 4096, 8192]
    aspect_ratios: [1.0]
    scale_ratios: [1.0]
    backbone_strides: [4, 8, 16, 32, 64]
    iou_threshold: 0.5
    score_threshold: 0.2
    nms_threshold: 0.2

backbone_params:
    num_layers: 50
    pretrained: True

subnet_params:
    num_layers: 4
