name: SSDTest

classes: [
    '.', 'х', 'ю', 'в', 'ч', 'р', 'и', 'п', 'ш', 'т', 'я', 'э',
    'о', 'ж', 'б', 'д', 'ц', 'е', '-', 'к', 'г', 'ф', 'а', 'й', '6', 'ы',
    'ё', 'л', '9', 'ъ', 'з', '0', 'с', '1', 'м', 'у', ',', 'н', 'щ', 'ь']

batch_size: 8
num_workers: 8

train:
    loss: SSDLoss
    epochs: 100
    model_dir: models
    log_dir: logs
    optimizer: Adam
    lr: 0.0001
    metrics: []

bbox_kwargs:
    image_size: [512, 512]
    areas: [64, 256, 1024, 2048, 4096]
    aspect_ratios: [1.0, 0.5, 2]
    scale_ratios: [1.0, 1.2599210498948732, 1.5874010519681994]
    backbone_strides: [4, 8, 16, 32, 64]
    iou_threshold: 0.5
    score_threshold: 0.2
    nms_threshold: 0.3

feature_extracter_kwargs:
    n_layers: 50
    pretrained: True

augmentation: hard
