classes: ['word']

data_params:
    batch_size: 8
    num_workers: 16

train_params:
    name: SSDFocalWord
    loss: FocalLoss
    loss_params:
        alpha: 1
        gamma: 2
    epochs: 100
    model_dir: models
    log_dir: logs
    optimizer: Adam
    optimizer_params:
        lr: 0.0003
    scheduler: StepLR
    scheduler_params:
        step_size: 20
        gamma: 0.5
    metrics: []

bbox_params:
    image_size: [512, 512]
    areas: [64, 256, 1024, 4096, 8192]
    aspect_ratios: [1.0, 0.25, 0.5]
    scale_ratios: [1.0, 1.2599210498948732, 1.5874010519681994]
    backbone_strides: [4, 8, 16, 32, 64]
    iou_threshold: 0.5
    score_threshold: 0.2
    nms_threshold: 0.2

backbone_params:
    num_layers: 101
    pretrained: True

subnet_params:
    num_layers: 4
